- project:
    name: alexey-mr/contrail-zuul-jobs
    check:
      jobs:
        - ci-test-core-centos-7
        - ci-test-contrail-core-centos-7
        - ci-test-packaging-centos-7
        - ci-test-lint-rpm-specs-centos-7
        - ci-test-ansible-lint-centos-7
        - ci-test-publish-infra-doc
        - ci-test-publish-infra-doc-unit
        - ci-test-publish-rpm-nexus
        - zuul-jobs-linters
        - noop:
            irrelevant-files:
              - ^roles/.*
              - ^playbooks/.*
              - ^tests/.*
    gate:
      queue: contrail-ci
      jobs:
        - ci-test-core-centos-7
        - ci-test-contrail-core-centos-7
        - ci-test-packaging-centos-7
        - ci-test-lint-rpm-specs-centos-7
        - ci-test-ansible-lint-centos-7
        - ci-test-publish-infra-doc
        - ci-test-publish-infra-doc-unit
        - ci-test-publish-rpm-nexus
        - zuul-jobs-linters
        - noop:
            irrelevant-files:
              - ^roles/.*
              - ^playbooks/.*
              - ^tests/.*
